GET http://localhost:5222/students/
Accept: application/json

###

POST http://localhost:5222/Students/Create/
Content-Type: application/x-www-form-urlencoded

name=name&number=number


### 

POST http://localhost:5222/Students/Update/a8425f67-88e0-4191-83ba-f5063d6b7811
Content-Type: application/x-www-form-urlencoded

name=Updated+name&number=Updated+number


###

POST http://localhost:5222/Students/PostDelete/a8425f67-88e0-4191-83ba-f5063d6b7811